//! `kong gui` — Native desktop GUI using Slint.
//!
//! Populates the UI with data from the store, RULEZ, and kong.rules files,
//! then hands off to the Slint event loop.

use std::path::{Path, PathBuf};

use anyhow::Result;
use slint::{ModelRc, SharedString, VecModel};

// Generated by build.rs from ui/kong.slint
slint::include_modules!();

use crate::config;
use crate::store;

/// A (name, version, ecosystem) -> list of project names mapping, used to compute cross-project usage.
type DepIndex = std::collections::HashMap<(String, String, String), Vec<String>>;

/// Build a cross-project dependency index: for each (ecosystem, name, version),
/// which projects use it.
fn build_dep_index(projects: &[(String, PathBuf)]) -> DepIndex {
    let mut index: DepIndex = std::collections::HashMap::new();

    for (proj_name, proj_path) in projects {
        let rules = match config::read_rules(&proj_path.join("kong.rules")) {
            Ok(r) => r,
            Err(_) => continue,
        };

        if let Some(ref py) = rules.python {
            for pkg in &py.packages {
                index.entry(("python".into(), pkg.name.clone(), pkg.version.clone()))
                    .or_default()
                    .push(proj_name.clone());
            }
        }
        if let Some(ref node) = rules.node {
            for pkg in &node.packages {
                index.entry(("node".into(), pkg.name.clone(), pkg.version.clone()))
                    .or_default()
                    .push(proj_name.clone());
            }
        }
        if let Some(ref rs) = rules.rust {
            for pkg in &rs.packages {
                index.entry(("rust".into(), pkg.name.clone(), pkg.version.clone()))
                    .or_default()
                    .push(proj_name.clone());
            }
        }
        if let Some(ref brew) = rules.brew {
            for pkg in &brew.packages {
                index.entry(("brew".into(), pkg.name.clone(), pkg.version.clone()))
                    .or_default()
                    .push(proj_name.clone());
            }
        }
    }

    index
}

/// Launch the GUI.
pub fn launch(project_dir: Option<&Path>) -> Result<()> {
    let window = KongWindow::new()?;

    // ── Populate initial data ────────────────────────────────────────────
    populate_all(&window, project_dir);

    // ── Wire callbacks ───────────────────────────────────────────────────
    {
        let w = window.as_weak();
        let pd = project_dir.map(|p| p.to_path_buf());
        window.on_refresh_data(move || {
            if let Some(win) = w.upgrade() {
                populate_all(&win, pd.as_deref());
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_service_start(move |name, project| {
            if let Some(win) = w.upgrade() {
                let proj_dir = resolve_project_dir(&project);
                match crate::service::start(Some(name.as_str()), None, &proj_dir) {
                    Ok(()) => {
                        win.set_status_message(SharedString::from(format!("✓ {} started", name)));
                        refresh_services(&win);
                    }
                    Err(e) => {
                        win.set_status_message(SharedString::from(format!("✗ {}", e)));
                    }
                }
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_service_stop(move |name, project| {
            if let Some(win) = w.upgrade() {
                let proj_dir = resolve_project_dir(&project);
                match crate::service::stop(Some(name.as_str()), &proj_dir) {
                    Ok(()) => {
                        win.set_status_message(SharedString::from(format!("✓ {} stopped", name)));
                        refresh_services(&win);
                    }
                    Err(e) => {
                        win.set_status_message(SharedString::from(format!("✗ {}", e)));
                    }
                }
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_service_start_all(move |_project| {
            if let Some(win) = w.upgrade() {
                let projects = discover_projects();
                for (name, path) in &projects {
                    let _ = crate::service::start(None, None, path);
                    let _ = name; // used for logging below
                }
                win.set_status_message(SharedString::from("✓ All services started"));
                refresh_services(&win);
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_service_stop_all(move |_project| {
            if let Some(win) = w.upgrade() {
                let projects = discover_projects();
                for (_name, path) in &projects {
                    let _ = crate::service::stop(None, path);
                }
                win.set_status_message(SharedString::from("✓ All services stopped"));
                refresh_services(&win);
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_show_service_logs(move |name, project| {
            if let Some(win) = w.upgrade() {
                let proj_dir = resolve_project_dir(&project);
                let lines = read_service_log(&name, &proj_dir, 100);
                let model: Vec<LogLine> = lines
                    .iter()
                    .map(|l| LogLine { text: SharedString::from(l.as_str()) })
                    .collect();
                win.set_service_log_lines(ModelRc::new(VecModel::from(model)));
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_run_script(move |script, project| {
            if let Some(win) = w.upgrade() {
                let proj_dir = resolve_project_dir(&project);
                match crate::runner::run(script.as_str(), &[], &proj_dir, false) {
                    Ok(()) => {
                        win.set_status_message(SharedString::from(format!("✓ {} finished", script)));
                    }
                    Err(e) => {
                        win.set_status_message(SharedString::from(format!("✗ {} — {}", script, e)));
                    }
                }
            }
        });
    }

    window.on_open_project_terminal(move |path| {
        let path_str = path.to_string();
        #[cfg(target_os = "macos")]
        {
            let _ = std::process::Command::new("open")
                .args(["-a", "Terminal", &path_str])
                .spawn();
        }
        #[cfg(target_os = "windows")]
        {
            let _ = std::process::Command::new("cmd")
                .args(["/C", "start", "cmd", "/K", &format!("cd /d {path_str}")])
                .spawn();
        }
    });

    {
        let w = window.as_weak();
        window.on_run_doctor(move || {
            if let Some(win) = w.upgrade() {
                let lines = run_doctor_lines();
                let model: Vec<LogLine> = lines
                    .iter()
                    .map(|l| LogLine { text: SharedString::from(l.as_str()) })
                    .collect();
                win.set_doctor_log_lines(ModelRc::new(VecModel::from(model)));
                win.set_status_message(SharedString::from("Doctor report ready"));
            }
        });
    }

    {
        let w = window.as_weak();
        let pd = project_dir.map(|p| p.to_path_buf());
        window.on_delete_project(move |project_name| {
            if let Some(win) = w.upgrade() {
                let proj_dir = resolve_project_dir(&project_name);
                // Clean RULEZ environment + project junctions
                let env_dir = store::rulez_dir(&project_name).ok();
                if let Some(ref ed) = env_dir {
                    let _ = crate::link::clean_environments(ed);
                }
                let _ = crate::link::clean_project_junctions(&proj_dir);
                // Remove the RULEZ directory for this project
                if let Some(ed) = env_dir {
                    let _ = std::fs::remove_dir_all(&ed);
                }
                win.set_status_message(SharedString::from(
                    format!("✓ Deleted environment for {}", project_name)
                ));
                populate_all(&win, pd.as_deref());
            }
        });
    }

    {
        let w = window.as_weak();
        window.on_select_project(move |project_name| {
            if let Some(win) = w.upgrade() {
                win.set_selected_project_name(project_name.clone());
                populate_packages(&win, &project_name);
            }
        });
    }

    // ── Run event loop ───────────────────────────────────────────────────
    window.run()?;
    Ok(())
}

// ── Data population ─────────────────────────────────────────────────────────

fn populate_all(window: &KongWindow, project_dir: Option<&Path>) {
    let projects = discover_projects();

    // Projects tab
    let project_infos: Vec<ProjectInfo> = projects
        .iter()
        .map(|(name, path)| {
            let rules = config::read_rules(&path.join("kong.rules")).ok();
            let scripts = rules
                .as_ref()
                .map(|r| {
                    let mut keys: Vec<&str> = r.scripts.keys().map(|k| k.as_str()).collect();
                    keys.sort();
                    keys.join(", ")
                })
                .unwrap_or_default();
            let has_services = rules.as_ref().map(|r| !r.services.is_empty()).unwrap_or(false);
            ProjectInfo {
                name: SharedString::from(name.as_str()),
                path: SharedString::from(path.to_string_lossy().as_ref()),
                scripts: SharedString::from(scripts.as_str()),
                has_services,
                status: SharedString::from("ready"),
            }
        })
        .collect();
    window.set_projects(ModelRc::new(VecModel::from(project_infos)));

    // If a project_dir was given, select it
    if let Some(pd) = project_dir {
        let name = pd
            .file_name()
            .map(|n| n.to_string_lossy().into_owned())
            .unwrap_or_default();
        window.set_selected_project_name(SharedString::from(name.as_str()));
    }

    // Services tab
    refresh_services(window);

    // Store tab
    populate_store(window);

    // Packages tab — populate if a project is selected
    let sel = window.get_selected_project_name();
    if !sel.is_empty() {
        populate_packages(window, &sel);
    }
}

fn refresh_services(window: &KongWindow) {
    let projects = discover_projects();
    let mut all_services: Vec<ServiceInfo> = Vec::new();

    for (proj_name, proj_path) in &projects {
        let rules = match config::read_rules(&proj_path.join("kong.rules")) {
            Ok(r) => r,
            Err(_) => continue,
        };

        if rules.services.is_empty() {
            continue;
        }

        let env_dir = match store::rulez_dir(proj_name) {
            Ok(d) => d,
            Err(_) => continue,
        };

        for svc in &rules.services {
            let svc_dir = env_dir.join("services").join(&svc.name);
            let pid_file = svc_dir.join("pid");
            let port_file = svc_dir.join("port");

            let pid = std::fs::read_to_string(&pid_file)
                .ok()
                .and_then(|s| s.trim().parse::<u32>().ok());

            let status = match pid {
                Some(p) => {
                    let alive = unsafe { libc::kill(p as i32, 0) == 0 };
                    if alive { "running" } else { "dead" }
                }
                None => "stopped",
            };

            let port = std::fs::read_to_string(&port_file)
                .ok()
                .map(|s| s.trim().to_string())
                .unwrap_or_else(|| svc.port.map_or("—".to_string(), |p| p.to_string()));

            let pid_str = pid.map_or("—".to_string(), |p| p.to_string());

            all_services.push(ServiceInfo {
                name: SharedString::from(svc.name.as_str()),
                project: SharedString::from(proj_name.as_str()),
                status: SharedString::from(status),
                port: SharedString::from(port.as_str()),
                pid: SharedString::from(pid_str.as_str()),
                brew_package: SharedString::from(svc.brew_package.as_str()),
            });
        }
    }

    window.set_services(ModelRc::new(VecModel::from(all_services)));
}

fn populate_store(window: &KongWindow) {
    let store_root = match store::store_root() {
        Ok(r) => r,
        Err(_) => return,
    };

    let mut items: Vec<StoreEntry> = Vec::new();

    // Scan each ecosystem
    for (ecosystem, subdir) in &[
        ("python", "python/libs"),
        ("node", "node/libs"),
        ("rust", "rust/crates"),
        ("brew", "brew"),
    ] {
        let dir = store_root.join(subdir);
        if !dir.exists() {
            continue;
        }
        if let Ok(entries) = std::fs::read_dir(&dir) {
            for entry in entries.flatten() {
                let path = entry.path();
                if !path.is_dir() {
                    continue;
                }
                let dir_name = path.file_name().unwrap_or_default().to_string_lossy().to_string();

                // Parse "name-version" from directory name
                let (name, version) = parse_name_version(&dir_name);

                // Get directory size (rough estimate — count entries)
                let size = dir_size_human(&path);

                items.push(StoreEntry {
                    ecosystem: SharedString::from(*ecosystem),
                    name: SharedString::from(name.as_str()),
                    version: SharedString::from(version.as_str()),
                    size: SharedString::from(size.as_str()),
                    store_path: SharedString::from(
                        format!("{}/{}", subdir, dir_name).as_str()
                    ),
                });
            }
        }
    }

    // Sort by ecosystem, then name
    items.sort_by(|a, b| {
        a.ecosystem.cmp(&b.ecosystem).then(a.name.cmp(&b.name))
    });

    window.set_store_items(ModelRc::new(VecModel::from(items)));
}

fn populate_packages(window: &KongWindow, project_name: &str) {
    let projects = discover_projects();
    let dep_index = build_dep_index(&projects);

    // Find the selected project and its dependencies
    let proj_path = projects
        .iter()
        .find(|(n, _)| n == project_name)
        .map(|(_, p)| p.clone());

    let proj_path = match proj_path {
        Some(p) => p,
        None => {
            window.set_package_deps(ModelRc::new(VecModel::from(Vec::<PackageDep>::new())));
            return;
        }
    };

    let rules = match config::read_rules(&proj_path.join("kong.rules")) {
        Ok(r) => r,
        Err(_) => {
            window.set_package_deps(ModelRc::new(VecModel::from(Vec::<PackageDep>::new())));
            return;
        }
    };

    let mut deps: Vec<PackageDep> = Vec::new();

    // Helper closure to add deps from a section
    let mut add_deps = |ecosystem: &str, packages: &[crate::config::PackageEntry]| {
        for pkg in packages {
            let key = (ecosystem.to_string(), pkg.name.clone(), pkg.version.clone());
            let used_by = dep_index.get(&key).cloned().unwrap_or_default();
            deps.push(PackageDep {
                ecosystem: SharedString::from(ecosystem),
                name: SharedString::from(pkg.name.as_str()),
                version: SharedString::from(pkg.version.as_str()),
                used_by_count: used_by.len() as i32,
                used_by: SharedString::from(used_by.join(", ").as_str()),
            });
        }
    };

    if let Some(ref py) = rules.python {
        add_deps("python", &py.packages);
    }
    if let Some(ref node) = rules.node {
        add_deps("node", &node.packages);
    }
    if let Some(ref rs) = rules.rust {
        add_deps("rust", &rs.packages);
    }
    if let Some(ref brew) = rules.brew {
        // Convert BrewEntry → PackageEntry-like for the closure
        let brew_as_pkg: Vec<crate::config::PackageEntry> = brew.packages.iter().map(|b| {
            crate::config::PackageEntry {
                name: b.name.clone(),
                version: b.version.clone(),
                hash: b.hash.clone(),
                store_path: b.store_path.clone(),
                source_url: b.source_url.clone(),
            }
        }).collect();
        add_deps("brew", &brew_as_pkg);
    }

    // Sort: shared deps first (descending by usage), then alphabetically
    deps.sort_by(|a, b| {
        b.used_by_count.cmp(&a.used_by_count)
            .then(a.ecosystem.cmp(&b.ecosystem))
            .then(a.name.cmp(&b.name))
    });

    window.set_package_deps(ModelRc::new(VecModel::from(deps)));
}

// ── Helpers ─────────────────────────────────────────────────────────────────

/// Discover all KONG-managed projects by scanning the RULEZ directory
/// and looking for projects that have a kong.rules file.
fn discover_projects() -> Vec<(String, PathBuf)> {
    let mut projects = Vec::new();

    // Method 1: Scan RULEZ directory for project names, then find their source dirs
    let rulez = match store::install_root() {
        Ok(root) => root.join("RULEZ"),
        Err(_) => return projects,
    };

    if !rulez.exists() {
        return projects;
    }

    if let Ok(entries) = std::fs::read_dir(&rulez) {
        for entry in entries.flatten() {
            let name = entry.file_name().to_string_lossy().to_string();
            // Try to find the project source directory
            // Check common locations
            for parent in &[
                dirs::home_dir().unwrap_or_default().join("Documents/GitHub"),
                dirs::home_dir().unwrap_or_default().join("Projects"),
                dirs::home_dir().unwrap_or_default().join("Developer"),
                std::env::current_dir().unwrap_or_default(),
            ] {
                let candidate = parent.join(&name);
                if candidate.join("kong.rules").exists() {
                    projects.push((name.clone(), candidate));
                    break;
                }
            }
        }
    }

    // Method 2: Current directory if it has kong.rules
    if let Ok(cwd) = std::env::current_dir() {
        if cwd.join("kong.rules").exists() {
            let name = cwd.file_name().unwrap_or_default().to_string_lossy().to_string();
            if !projects.iter().any(|(n, _)| n == &name) {
                projects.push((name, cwd));
            }
        }
    }

    projects.sort_by(|a, b| a.0.cmp(&b.0));
    projects
}

fn resolve_project_dir(project_name: &str) -> PathBuf {
    let projects = discover_projects();
    projects
        .iter()
        .find(|(n, _)| n == project_name)
        .map(|(_, p)| p.clone())
        .unwrap_or_else(|| std::env::current_dir().unwrap_or_default())
}

fn read_service_log(service_name: &str, project_dir: &Path, max_lines: usize) -> Vec<String> {
    let project_name = project_dir
        .file_name()
        .map(|n| n.to_string_lossy().into_owned())
        .unwrap_or_default();

    let env_dir = match store::rulez_dir(&project_name) {
        Ok(d) => d,
        Err(_) => return vec!["Error: could not find RULEZ directory".to_string()],
    };

    let log_file = env_dir.join("services").join(service_name).join("log");
    if !log_file.exists() {
        return vec![format!("No log file for {service_name} yet.")];
    }

    match std::fs::read_to_string(&log_file) {
        Ok(content) => {
            let all_lines: Vec<&str> = content.lines().collect();
            let start = all_lines.len().saturating_sub(max_lines);
            all_lines[start..].iter().map(|s| s.to_string()).collect()
        }
        Err(e) => vec![format!("Error reading log: {e}")],
    }
}

fn run_doctor_lines() -> Vec<String> {
    let mut lines = Vec::new();

    match store::doctor() {
        Ok(report) => {
            lines.push(format!("Store: {}", report.store_path.display()));
            if report.store_exists {
                lines.push(format!("  ✓ Python packages: {}", report.python_count));
                lines.push(format!("  ✓ Node packages: {}", report.node_count));
                lines.push(format!("  ✓ Rust crates: {}", report.rust_count));

                // Count brew
                let brew_dir = report.store_path.join("brew");
                if brew_dir.exists() {
                    let count = std::fs::read_dir(&brew_dir)
                        .map(|e| e.filter_map(|x| x.ok()).filter(|x| x.path().is_dir()).count())
                        .unwrap_or(0);
                    lines.push(format!("  ✓ Brew bottles: {}", count));
                }
            } else {
                lines.push("  ✗ Store does not exist".to_string());
            }

            if report.issues.is_empty() {
                lines.push("  ✓ No issues found".to_string());
            } else {
                for issue in &report.issues {
                    lines.push(format!("  ✗ {issue}"));
                }
            }
        }
        Err(e) => {
            lines.push(format!("Error running doctor: {e}"));
        }
    }

    // Check RULEZ
    if let Ok(root) = store::install_root() {
        let rulez = root.join("RULEZ");
        if rulez.exists() {
            let count = std::fs::read_dir(&rulez)
                .map(|e| e.filter_map(|x| x.ok()).filter(|x| x.path().is_dir()).count())
                .unwrap_or(0);
            lines.push(format!("  ✓ RULEZ: {} project environments", count));
        }
    }

    lines
}

/// Parse "flask-3.1.1" or "postgresql@17-17.9" into (name, version).
fn parse_name_version(dir_name: &str) -> (String, String) {
    // Try to find the last '-' followed by a digit (version separator)
    if let Some(idx) = dir_name.rfind(|c: char| c == '-')  {
        let after = &dir_name[idx + 1..];
        if after.starts_with(|c: char| c.is_ascii_digit()) {
            return (dir_name[..idx].to_string(), after.to_string());
        }
    }
    (dir_name.to_string(), String::new())
}

/// Rough directory size in human-readable form.
fn dir_size_human(path: &Path) -> String {
    let mut total: u64 = 0;
    if let Ok(walker) = walkdir::WalkDir::new(path).into_iter().try_for_each(|entry| {
        if let Ok(e) = entry {
            if e.file_type().is_file() {
                total += e.metadata().map(|m| m.len()).unwrap_or(0);
            }
        }
        Ok::<(), ()>(())
    }) {
        let _ = walker;
    }

    if total < 1024 {
        format!("{total} B")
    } else if total < 1024 * 1024 {
        format!("{:.0} KB", total as f64 / 1024.0)
    } else if total < 1024 * 1024 * 1024 {
        format!("{:.1} MB", total as f64 / (1024.0 * 1024.0))
    } else {
        format!("{:.1} GB", total as f64 / (1024.0 * 1024.0 * 1024.0))
    }
}
